// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by synquill aggregate_builder

import 'package:synquill/synquill.dart';
import 'package:synquill/synquill_core.dart'
    show DatabaseAccessor, GeneratedDatabase;
import 'test_models/contact.dart';
import 'test_models/post.dart';
import 'test_models/local_note.dart';
import 'test_models/plain_model.dart';
import 'test_models/user.dart';
import 'test_models/relation_indexing_validation_test_models.dart';
import 'test_models/category.dart';
import 'test_models/test_server_id_model.dart';
import 'test_models/department.dart';
import 'test_models/todo.dart';
import 'test_models/project.dart';
import 'test_models/company.dart';
import 'generated/database.generated.dart';
export 'generated/database.generated.dart';

part 'generated/repositories.g.dart';
part 'generated/api_adapters.g.dart';
part 'generated/model_extensions.g.dart';
