export 'package:synquill/synquill.dart';
export 'user.dart';
export 'todo.dart';
export 'post.dart';
export 'plain_model.dart';
export 'contact_base.dart';
export 'local_note.dart';
export '../adapters/json_api_adapter.dart';
export '../synquill.generated.dart';
