name: synquill_utils
description: Utils for code generator and for the Offline-first Dart data engine with background JSON API sync and custom retry logic.
version: 0.5.0
homepage: https://synquill.dev

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
