name: synquill_gen
description: Code generator for the Offline-first Flutter data engine with background JSON API sync and custom retry logic.
version: 0.1.0
homepage: https://synquill.dev

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  analyzer: any # For code analysis in builder
  build: ^2.4.2
  build_resolvers: any # For testing builders
  drift_dev: ^2.26.1
  glob: ^2.1.3
  json_serializable: ^6.9.5
  logging: ^1.3.0
  meta: ^1.16.0
  source_gen: ^2.0.0
  synquill:
    git:
      url: https://github.com/andreystavitsky/synquill.git
      ref: 0a74d18fda3976b97af2cfe65d4782dad7dac663
      path: synquill

dev_dependencies:
  build_runner: ^2.4.15
  build_test: any # For testing builders
  flutter_lints: ^5.0.0
  lints: ^5.0.0
  mockito: any
  test: ^1.24.0
