name: synquill_gen
description: Code generator for the Synquill library.
version: 0.5.1
homepage: https://synquill.dev
repository: https://github.com/andreystavitsky/synquill

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  analyzer: '>=7.3.0 <8.0.0'
  build: ^2.4.2
  build_resolvers: ^2.4.0
  drift_dev: ^2.26.1
  glob: ^2.1.3
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  logging: ^1.3.0
  meta: ^1.16.0
  source_gen: ^2.0.0
  synquill_utils: ^0.5.0

dependency_overrides:
  analyzer: '>=7.3.0 <7.4.0'

dev_dependencies:
  build_runner: ^2.4.14
  build_test: ^2.2.3
  lints: ^6.0.0
  test: ^1.24.0
