include: package:lints/recommended.yaml

linter:
  rules:
    # ERROR RULES
    # Style
    avoid_print: true
    prefer_single_quotes: true
    prefer_double_quotes: false # Conflicts with prefer_single_quotes
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    package_prefixed_library_names: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_new: true
    unnecessary_const: true
    unnecessary_this: true
    unawaited_futures: true
    # Documentation
    public_member_api_docs: true # Enforce for public APIs as per spec
    # Pub
    sort_pub_dependencies: true

    # WARNING RULES
    # Style
    lines_longer_than_80_chars: true
    

analyzer:
  exclude:
    - '**/*.g.dart' # Exclude generated files
    - '**/*.freezed.dart' # Exclude generated files
    - '**/*.mocks.dart' # Exclude generated files
  errors:
    # treat missing required parameters as an error
    missing_required_param: error
    use_string_in_part_of_directives: ignore
    unnecessary_library_name: ignore
    lines_longer_than_80_chars: warning 
    unawaited_futures: error

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
