targets:
  $default:
    sources:
      include:
        - lib/**
        - test/**
        - pubspec.*
        - $package$
      exclude:
        - example/**
    builders:
      synquill_gen|aggregateBuilder:
        enabled: false
