name: synquill
description: Offline-first Flutter data engine with background JSON API sync and custom retry logic.
version: 0.1.0
homepage: https://synquill.dev

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cuid2: ^3.1.0
  dio: ^5.8.0+1
  drift: ^2.26.1
  flutter:
    sdk: flutter
  flutter_secure_storage: any
  glob: ^2.1.3
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0
  queue: ^3.4.0
  stream_transform: ^2.1.1
  #sqlcipher_flutter_libs: ^0.6.6

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^6.0.0
  mockito: any
  synquill_gen:
    path: ../synquill_gen
  test: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


