name: synquill
description: Offline-first Flutter data engine with background JSON API sync and custom retry logic.
version: 0.5.0
homepage: https://synquill.dev

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cuid2: ^3.1.0
  dio: ^5.8.0+1
  drift: ^2.26.1
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.3.0
  queue: ^3.4.0
  stream_transform: ^2.1.1
  synquill_utils:
    path: ../synquill_utils
  #sqlcipher_flutter_libs: ^0.6.6

dev_dependencies:
  build_runner: ^2.4.14
  lints: ^6.0.0
  mockito: any
  synquill_gen:
    path: ../synquill_gen
  test: any
