// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by synquill aggregate_builder

import 'package:synquill/synquill.dart';
import 'package:synquill/synquill_core.dart' show 
  DatabaseAccessor, GeneratedDatabase;
import 'package:synquill_graphql/synquill_graphql.dart';
import 'package:synquill_example/models/graphql_post.dart';
import 'package:synquill_example/models/post.dart';
import 'package:synquill_example/models/local_note.dart';
import 'package:synquill_example/models/plain_model.dart';
import 'package:synquill_example/models/user.dart';
import 'package:synquill_example/models/todo.dart';
import 'package:synquill_example/models/favorite_place.dart';
import 'package:synquill_example/adapters/json_api_adapter.dart';
import 'package:synquill_example/generated/database.generated.dart';
export 'package:synquill_example/generated/database.generated.dart';

part 'generated/repositories.g.dart';
part 'generated/api_adapters.g.dart';
part 'generated/model_extensions.g.dart';

