// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by synquill aggregate_builder

import 'package:synquill/synquill.dart';
import 'package:synquill/synquill_core.dart' show 
  DatabaseAccessor, GeneratedDatabase;
import 'models/post.dart';
import 'models/local_note.dart';
import 'models/plain_model.dart';
import 'models/user.dart';
import 'models/todo.dart';
import 'adapters/json_api_adapter.dart';
import 'generated/database.generated.dart';
export 'generated/database.generated.dart';

part 'generated/repositories.g.dart';
part 'generated/api_adapters.g.dart';
part 'generated/model_extensions.g.dart';

